[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc2\0\0\0\x37\0\0\au\0\0\x4-\0\0\x3\xc2\0\0\0\x37\0\0\au\0\0\x4-\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc2\0\0\0\x37\0\0\au\0\0\x4-)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3\xb4\0\0\x3\xf7\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=false
donation_message=false
show_msg=true
show_name=true
show_photo=true

[onboarding]
completed=true
last_environment=local
version=2

[system]
menubar=false
quit_in_close=true
sidebar=false
spellCheckers=true
start_background=false
start_system=false
theme=dark
tray_theme=symbolic_dark
wayland=false

[website]
open_page=false
