hl.on("hyprland.start", function () 
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("waybar")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("swaync")
  hl.exec_cmd("pypr")
  hl.exec_cmd("swaync-client -df")
  hl.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ 0")
  hl.exec_cmd("hyprctl setcursor Adwaita 24")
end)