#!/bin/bash

# cargar colores de wal
. "$HOME/.cache/wal/colors.sh"

# crear tema para btop
mkdir -p ~/.config/btop/themes

cat > ~/.config/btop/themes/wal.theme <<EOF
theme[main_bg]="$background"
theme[main_fg]="$foreground"

theme[title]="$color4"
theme[hi_fg]="$color6"
theme[selected_bg]="$color2"
theme[selected_fg]="$background"

theme[inactive_fg]="$color8"
theme[graph_text]="$color2"
theme[meter_bg]="$color8"

theme[proc_misc]="$color5"
theme[cpu_box]="$color1"
theme[mem_box]="$color2"
theme[net_box]="$color4"
theme[proc_box]="$color5"
EOF
