theme[main_bg]="#070000"
theme[main_fg]="#F3FAE6"

theme[title]="#C1D5FF"
theme[hi_fg]="#DDF0B8"
theme[selected_bg]="#C1D5FF"
theme[selected_fg]="#070000"

theme[inactive_fg]="#A1A794"
theme[graph_text]="#AB89A2"
theme[meter_bg]="#A1A794"

theme[proc_misc]="#FFD2BD"
theme[cpu_box]="#549E3F"
theme[mem_box]="#AB89A2"
theme[net_box]="#C1D5FF"
theme[proc_box]="#FFD2BD"

theme[div_line]="#A1A794"

theme[temp_start]="#AB89A2"
theme[temp_mid]="#45BCB8"
theme[temp_end]="#549E3F"

theme[cpu_start]="#AB89A2"
theme[cpu_mid]="#45BCB8"
theme[cpu_end]="#549E3F"

theme[free_start]="#AB89A2"
theme[free_mid]="#45BCB8"
theme[free_end]="#549E3F"

theme[cached_start]="#DDF0B8"
theme[cached_mid]="#C1D5FF"
theme[cached_end]="#FFD2BD"

theme[available_start]="#AB89A2"
theme[available_mid]="#DDF0B8"
theme[available_end]="#C1D5FF"

theme[used_start]="#45BCB8"
theme[used_mid]="#549E3F"
theme[used_end]="#FFD2BD"

theme[download_start]="#DDF0B8"
theme[download_mid]="#C1D5FF"
theme[download_end]="#AB89A2"

theme[upload_start]="#FFD2BD"
theme[upload_mid]="#549E3F"
theme[upload_end]="#45BCB8"
