foreground         #c1c3c3
background         #071012
background_opacity 1.0
cursor             #c1c3c3

active_tab_foreground     #071012
active_tab_background     #c1c3c3
inactive_tab_foreground   #c1c3c3
inactive_tab_background   #071012

active_border_color   #c1c3c3
inactive_border_color #071012
bell_border_color     #1f3c3c

color0       #071012
color8       #56676a
color1       #1f3c3c
color9       #2a5151
color2       #23403f
color10      #2f5654
color3       #36534e
color11      #496f68
color4       #4a665c
color12      #63897b
color5       #4b675e
color13      #648a7e
color6       #4d685d
color14      #678b7c
color7       #8c9496
color15      #c1c3c3
